### PR TITLE
Key to local storage

### PR DESCRIPTION
**Pull request by StinaSoile**
Progress key is now saved in local storage and read from there.

### CODE REVIEW

**Comment by sepi4** [comment]
image

commit messages need always have short description 

read this 
https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by sepi4** [comment]
image

**Comment by sepi4** [comment]
try to figure out how to fix commit messages :)

**Comment by StinaSoile** [comment]
done

**Review by sepi4 — APPROVED** [review]
good

**Pull request merged**
